// Generated by CoffeeScript 1.6.3
  (function() {
    var key, val, _ref, _results;
    _ref = require('./coffee-script');
    _results = [];
    for (key in _ref) {
      val = _ref[key];
      _results.push(exports[key] = val);
    }
    return _results;
  })();
